### ISSUE TITLE
Group with gitlab main repo and github mirrors seems to confuse libraries.io, the main group page with "gitlab" in path links to github projects

### ISSUE THREAD

**Issue by JonasT** [librariesio/libraries.io#1220]
A group I manage with multiple subprojects which exists both on gitlab (main repos - https://gitlab.com/ChiCraft/ ) and on github (official mirrors - https://github.com/ChiCraft/ ) seems to confuse libraries.io:

When explicitely accessing the gitlab-related page https://libraries.io/gitlab/ChiCraft/ , I get the github projects listed instead. Also, there seems to be no way to access the actual original main repo info directly: https://libraries.io/gitlab/ChiCraft/stdlib (gives me a 404 error)

**Comment by andrew** [comment]
Gitlab and Bitbucket support has only just been added, we've not quite finished the users/orgs importing, open issue for that: https://github.com/librariesio/libraries.io/issues/1171

I've just deployed a "fix" that makes https://libraries.io/gitlab/ChiCraft 404 rather than show the GitHub equivalent org.

https://libraries.io/gitlab/ChiCraft/stdlib is currently 404ing as Libraries.io is still crawling gitlab for open source projects and hasn't reached yours yet, should get to it within the next week or so I think
