### ISSUE TITLE
Community Action Lists

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1416]
Thought I'd write up this idea after chatting about it with @joshsimmons and @BenJam last week.

I recently pulled [some data](https://gist.github.com/andrew/2241138a715cd650703f0d4697618f86) from the Libraries.io database to help @olivierlacan find all the rubygems that have a changelog now that https://github.com/rubygems/rubygems.org/pull/1553 has been merged. 

This resulted in a dataset of 18K gems with changelogs that could benefit from the new feature and just needed a simple addition to their `*.gemspec` files ([like this](https://github.com/splitrb/split/commit/ddaa62c987225f9a83de94ae39058801010a8b1a))

The final step is to enable a way to point an eager group of contributors at the list of projects to update and give them a way to mark off the ones that have been fixed (or at least are in progress with an open pull request) and the ones that have been investigated and can't be fixed (deleted repo or awol maintainer for example).

I've been calling that final step a "community action list"

@kemitchell did a similar thing for licenses of the 1000 most-depended-upon (dependent projects in Libraries.io terms) npm modules: https://npm1k.org/

And Google recently did something similar with Operation Rosehub to fix java security issues, although I believe it was only open to Google developers rather than the community at large:  https://opensource.googleblog.com/2017/03/operation-rosehub.html

We also have a number of list on the site already that kinda form action lists although don't have any interaction to them:

- https://libraries.io/bus-factor
- https://libraries.io/unlicensed-libraries
- https://libraries.io/unseen-infrastructure

Also a couple that focus on individual issues rather than whole projects:

- https://libraries.io/help-wanted
- https://libraries.io/first-pull-request

Some potential action lists that Libraries.io has data for that could be made from:

- open source repositories that depend upon a version of an npm module with a known vulnerability cc @evilpacket 
- Permissively licensed repositories that have copyleft licensed dependencies and may be in violation of the GPL cc @joshsimmons for intro to someone at the FSF
 - Repositories that have a lot of contributors but no CODE_OF_CONDUCT file
- Libraries that depend on yanked/removed projects that need to switch to a different library
- Projects that don't have a readme or any kind of documentation

There's a lot of potential scope for a feature like this, including some kind of gamification or "magic internet points" similar to stackoverflow to give people a nudge to contribute but to begin with I propose we make one action list and have the ability to mark it as in progress and add a note to each item on the list and go from there.

I imagine also having a way to request the creation of an new community action list, via email to begin with, expanding to enable users/moderators to create their own in the future either via csv upload or some kind of query DSL to the Libraries.io datasets that would enable it to update lists automatically as it seems changes happening on GH/GL/BB

Would love to hear thoughts, feedback, potential action lists ideas before kicking off any development.

**Comment by kemitchell** [comment]
https://github.com/npm1k has code.  I have the update script in a cron job, because there's no reason to turn it off.  The percentage is very stable.

I don't regret the project, but I am not happy about the "gamification" aspects of it, or what it came to be.  Name-and-shame isn't a great operating principle.  Neither is making it easy for rando developers to accumulate GitHub stats on popular packages by running down a list.

The project started as a script that created pull requests to add license metadata automatically, with a templated pull request message, under my personal GitHub account.  Most of those PRs are still open, with no responses.  Those that did get closed out, I followed up on personally, as I said I would in my message.  That was a lot of work.

Others who followed, using npm1k as a hit list, were far less considerate.  There were a lot of copy-and-paste pull requests with little or no communication beyond a link back to npm1k.org.  Sure, it's just a one-line metadata patch.  But that makes the experience on the receiving end worse for many.  Random dev busts into your project just to correct you on a minor point.  A few of them got the metadata value wrong, and had to be corrected.

Tons of packages have had their license metadata corrected.  But the code that made the difference was a warning message from the npm command-line interface.  That worked so well that I went back and PR'd validation to `gem`, as well.

Folks like their code to be Correct, whatever that means this week.  And they like clean terminal output.  Making them aware there's a convention or a feature, so they can opt into it themselves, is highly preferable to waging a campaign upon maintainers.  A campaign can end up gamified, whether you gamify your part of it or not.

**Comment by tombh** [comment]
This is such a powerful idea and one it appears libraries.io is in a unique position to address. Firstly because libraries.io has the relevant sources of indexed data, but also because it is a non-partisan and non-profit organisation.

Taking @kemitchell's first-hand experience into account perhaps a first step could be just static lists, like the bus factor one, etc. Perhaps that would be enough to get people sharing these lists and starting conversations. Naming and shaming is certainly not the best motivation. I think libraries.io already has a demonstrated sensitivity to the practices and culture that encourages constructive, realistic and inclusive open source environments. And I'm sure that can be reflected in the approach to these Community Lists.

Another point of course is that different lists require different approaches, for instance I can imagine "positive lists", where instead of fixing something you're rewarding a person or dependency for significant contributions. In which case naming and "honouring" would be more appropriate for gamification.

**Comment by samjacobclift** [comment]
Out of interest how can libraries determine `Libraries that depend on yanked/removed projects that need to switch to a different library`?

**Comment by andrew** [comment]
@samjacobclift some package managers have fields/responses that say "yanked", we also have rake tasks that check for 404s on the package manager websites: https://github.com/librariesio/libraries.io/blob/master/lib/tasks/projects.rake#L49-L74

**Comment by samjacobclift** [comment]
ah nice

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
