### ISSUE TITLE
Support domain-specific keywords

### ISSUE THREAD

**Issue by choldgraf** [librariesio/libraries.io#1675]
I think it'd be really helpful for people in the scientific community if there were keywords based on scientific / analytic domain (e.g., geospatial analytics, neuroscience) as opposed to the more functional computer-sciencey keywords that are there (e.g., API, wrapper, etc). Any plans to do something like this?

One idea that comes to mind is not to support this explicitly, but do improve the search algorithm in order to find packages that are conceptually related even if the search phrase doesn't explicitly show up with the package. If there's already a dependency tree that (I assume) is used in generating search results, perhaps it could be supported by an idea of project similarity based on the content of their READMEs, documentation, etc.

**Comment by andrew** [comment]
@choldgraf at the moment all the keywords come from being specified in the libraries that are indexed, looks like there are 46 projects tagged `neuroscience`: https://libraries.io/keywords/neuroscience

The problem seems to be more around the UI only showing the most popular keywords in the search UI:

![screen shot 2017-08-30 at 4 27 47 pm](https://user-images.githubusercontent.com/1060/29880629-2dda3286-8da0-11e7-916e-f3b329cf8651.png)

Those keywords should really be only the ones that are related to the projects from the search results, I wonder if we can get elasticsearch to do that automatically when faceting.

**Comment by choldgraf** [comment]
ahh I see - I didn't notice that there were non-language-specific keywords later in the list...

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
