### ISSUE TITLE
Incorrect Python Dependencies

### ISSUE THREAD

**Issue by gsauthof** [librariesio/libraries.io#2136]
Example pdfrw: https://libraries.io/pypi/pdfrw

Curently, the page claims 'Dependent Packages: 0' but many Python packages depend on it (as can be seen by the 'Dependent repositories: 110' lines).

Example inema: https://libraries.io/pypi/inema

The page is missing a 'Dependencies' line but the setup.py contains a  few dependencies:

    install_requires = [
        'zeep >= 0.12.0',
        'lxml',
    ]
    # ...
    install_requires=install_requires,

Also, the line 'Total releases: 0' is wrong - there was one release; cf. https://pypi.org/project/inema/#history

Example img2pdf: https://libraries.io/pypi/img2pdf

The page has:

    Dependencies 0 
    Dependent Package  0

This is incorrect. The setup.py lists one dependency:

    INSTALL_REQUIRES = (     'Pillow', )
    # ...
    install_requires=INSTALL_REQUIRES,

Again, although the page lists 30 'Dependent repositories', it claims that there zero 'Dependent Packages'.

**Comment by movermeyer** [comment]
**Disclaimer:** I'm not a maintainer of libraries.io

---

Total releases doesn't count the 0.1 version. This is because libraries.io uses the data returned by [PyPI's JSON API for `inema`](https://pypi.org/pypi/inema/json). For the 0.1 release PyPI returns `[]`, which is [explicitly ignored](https://github.com/librariesio/libraries.io/blob/860afa482f841a82115d3e148d2f28815fcc9bed/app/models/package_manager/pypi.rb#L52) by libraries.io (though I'm not sure why).

---

Python dependency parsing is done by the [pydeps](https://github.com/librariesio/pydeps) server. The dependencies are not listed since [pydeps seems to have some trouble with inema](http://pip.libraries.io/inema/0.3.json). I haven't yet run the pydeps server to figure out what specifically is failing.

**Comment by katzj** [comment]
Fixed up pydeps (https://github.com/librariesio/pydeps/pull/3) so as things resync they will get fixed here

**Comment by gsauthof** [comment]
Did the resync already happened for all packages?

The page still lists 0 dependent packages:

https://libraries.io/pypi/pdfrw
https://libraries.io/pypi/pdfrw/dependents

The inema page looks good now.
