### ISSUE TITLE
Keyword parsing for PyPi merges all keywords into one string

### ISSUE THREAD

**Issue by fridde** [librariesio/libraries.io#2507]
## Bug
On the page for the Python project [Watchdog](https://libraries.io/pypi/watchdog) the keywords are given as just one single string without commas in between.

Yet checking the corresponding [PyPi project page](https://pypi.org/project/watchdog/0.10.2/) (left sidebar, "Meta"), the keywords given there seem just fine, all separated by commas.

I checked what I believe to be the corresponding parser [at this line](https://github.com/librariesio/libraries.io/blob/65d32c8833f407ce6c2ccec2a92c0ef74b77ab9d/app/models/package_manager/pypi.rb#L48) but it looks alright to me.

Does anyone have an idea where things could have gone wrong?

EDIT: [This project](https://libraries.io/pypi/lazydog) is another weird example of keyword parsing gone wrong.

**Comment by katzj** [comment]
It looks like the [metadata for watchdog](https://pypi.org/pypi/watchdog/json) uses spaces to separate keywords instead of commas. And it looks like the [spec has changed](https://github.com/pypa/packaging.python.org/commit/e2b5a3b9127cb05d50c188df80bd44f65d8d176f)

Will update the parsing to handle both 🤷‍♂️
