### ISSUE TITLE
Delete deleted GitHub repositories

### ISSUE THREAD

**Issue by pjanx** [librariesio/libraries.io#2580]
## Bugs
libraries.io contains deleted GitHub repositories, even from deleted GitHub users.

Relates to:
https://github.com/librariesio/libraries.io/issues/2258
https://github.com/librariesio/libraries.io/issues/2014

It is not sustainable to keep doing this manually, per request.

## Enhancements and Features
Scan GitHub projects and deindex them when a 404 is received.

At minimum mark them as defunct.

**Comment by katzj** [comment]
In general, the repos were there so someone could be using them so we keep the data around. We also can't reasonably rescan all of github and are dependent on notifications which we only get for thigns which still exist.

**Comment by pjanx** [comment]
You mean you can't afford to issue a single HEAD request for the subset you hold?

**Comment by nEMKJp** [comment]
One option might be to give account owners (or just any ol' page vistor) the ability to refresh stale data from the source (throttled) instead of handling it manually via an issue queue.

Or at least create a github issue queue bot to automate your job here. Let me know if i can help or if this is something your simply not interested in for the project.
