### ISSUE TITLE
please remove already deleted repos

### ISSUE THREAD

**Issue by brickheck236** [librariesio/libraries.io#2689]
Please remove the following repos since I already removed them from my repo, along with the github user.

https://libraries.io/github/titanopython/training-repo
https://libraries.io/github/greenwaffle/hello-world
https://libraries.io/github/greenwaffle/greenwaffle.github.io

Thanks.

**Comment by nEMKJp** [comment]
There is quite a bit of responsibility for collecting this data, both legal (GDPR, CCPA, DMCA) and also just being a decent netizen.

Instead of dealing with with this, its probably best to push those types of responsibilities to the source of the data where it can be handled more comprehensively.

If libraries.io would rather hord the deleted data you then own the responsiblity. I'm in the same boat as @brickheck236 is a github issue the way to go about such a request?

It's probably best to give account owners (or just any ol' page vistor) the ability to refresh stale data from the source (throttled). Let me know if I can contribute to this in any way.

**Comment by katzj** [comment]
Removed
