### ISSUE TITLE
RSS Feeds seem to all throw 403 Forbidden?

### ISSUE THREAD

**Issue by TLop503** [librariesio/libraries.io#3130]
## When attempting to access RSS feeds for packages and whatnot, I run into 403 forbidden codes.
I am trying to scrape updates for packages my workplace uses into a MS Teams channel so we can conveniently see when new versions are released.

### Steps to re-create:
Click any RSS feed button on a "versions" page, or a link intended for RSS feeds.
Example: https://libraries.io/npm/@types/node/versions.atom

### Issue
These links consistently throw 403 errors. It's very possible I'm misunderstanding the usage of these addresses, but I am unable to access them manually or from RSS clients such as the Microsoft Teams plugin. Is there a solution to this I can handle or is this an issue with the feed itself? 

Thanks for taking the time to read this.

**Comment by mertaytore** [comment]
Hey @TLop503 👋🏼 I'm not one of the maintainers of this project but wanted to chip in when I saw the issue above -

When I had a brief look at what the RSS feed button does via my browser's devtools in an incognito window, it looks like it's asking the user to be authenticated in order to present the list of RSS feeds which very likely what you're missing here.

> scrape updates for packages my workplace uses into a MS Teams channel so we can conveniently see when new versions are released.

However, after going through the initial problem that you're looking to solve, I came across [libraries.io's API](https://libraries.io/api) where they conveniently [let you subscribe to projects](https://libraries.io/api#subscriptions-create) by using your API key which can be found under [/account endpoint](https://libraries.io/account). I hope this is helpful!
