### ISSUE TITLE
Allow users to rate/review projects 

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#37]
Allow people to leave reviews or star ratings on projects, mostly to highlight poor quality projects.

**Comment by eloquence** [comment]
If this is still of interest: I'm working on a freely licensed/open source/non-profit platform for reviews of anything, and I'm treating developer tools and libraries as a high priority use case since there are limited options for those today. I'm currently focused on supporting the http://f-droid.org/ use case (see https://gitlab.com/fdroid/fdroidclient/issues/646 for discussion) but I'd be happy to also consider libraries.io as an integration use case. As with F-Droid, I'd want to initially do it as a semi-closed beta until we're confident that it's working as intended. Let me know if you want to collaborate :)

**Comment by andrew** [comment]
Moving to the backlog: https://github.com/librariesio/libraries.io/blob/master/Backlog.md
