### ISSUE TITLE
bower search

### ISSUE THREAD

**Issue by andrewplummer** [librariesio/libraries.io#883]
Hi, I've noticed that https://bower.io/search/ has been caching packages for a long time without refreshing (like, months). Is this a bug, or something intentional?

**Comment by andrew** [comment]
@andrewplummer do you have an example of a package?

**Comment by andrewplummer** [comment]
Yes! Sorry, should have given more details. I reached out to the owner of `sugar-string` and moved his package to [my repo](http://github.com/andrewplummer/sugar-string.git), however the search is still pointing to [the old one](https://github.com/EvanWieland/sugar-string). This should be almost 2 months ago. I thought I remembered some other packages, but this is the best example.

**Comment by andrew** [comment]
I've updated https://libraries.io/bower/sugar-string for you and kicked off a task to make sure there aren't any others that have been missed, I suspect that one didn't change automatically because there is no easy way for Libraries.io to know about changes to existing bower projects (i.e. they swapped repos), will have to setup a regular task to check for changed/outdated ones

**Comment by andrew** [comment]
I've left myself a task to do that here: https://github.com/librariesio/libraries.io/issues/884

**Comment by andrewplummer** [comment]
Thank you! Actually there's one more: https://libraries.io/bower/sugar-date if you would be so kind?

**Comment by andrew** [comment]
@andrewplummer updated: https://libraries.io/bower/sugar-date

**Comment by andrewplummer** [comment]
Thank you!
